services:
  dev:
    build:
      context: .
      dockerfile: Dockerfile
      target: dev
    image: gelos-lc-dev
    environment:
      NB_UID: "${UID:-1000}"
      NB_GID: "${GID:-100}"
      NB_USER: jovyan
      CHOWN_HOME: "yes"
      CHOWN_HOME_OPTS: "-R"
      GRANT_SUDO: "yes"
      PYTHONPATH: /app
    working_dir: /app
    ports:
      - "${JUPYTER_HOST_PORT:-8888}:8888"
      - "${DASK_HOST_PORT:-8787}:8787"
    volumes:
       - ./:/app/ 
       - "${RAW_PATH}:/app/data/raw/"
       - "${PROCESSED_PATH}:/app/data/processed/"
       - "${EXTERNAL_PATH}:/app/data/external/"
       - "${INTERIM_PATH}:/app/data/interim/"
       - "${GELOS_MODULE_PATH}:/app/gelos/"
       - "./docker/10-install-gelos.sh:/usr/local/bin/before-notebook.d/10-install-gelos.sh:ro"
    shm_size: '32gb'
    command: "start-notebook.py ${JUPYTERLAB_ARGS}"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
   
  test:
    build:
      context: .
      dockerfile: Dockerfile
      target: test
    image: gelos-lc-test
    user: "${UID}:${GID}"
    environment:
      PYTHONPATH: /app
      HOME: /tmp
    working_dir: /app

  prod:
    build:
      context: .
      dockerfile: Dockerfile
      target: prod
    image: gelos-lc-prod
    user: "${UID}:${GID}"
    environment:
      PYTHONPATH: /app 
      HOME: /tmp
      TORCHINDUCTOR_CACHE_DIR: /tmp/torch_cache
    working_dir: /app
    volumes:
      - "${RAW_PATH}:/app/data/raw/"
      - "${PROCESSED_PATH}:/app/data/processed/"
      - "${EXTERNAL_PATH}:/app/data/external/"
      - "${INTERIM_PATH}:/app/data/interim/"
      - "./scripts/:/app/scripts/"
      - "./configs/:/app/configs/"
      - "./lightning_logs/:/app/lightning_logs/"
    shm_size: '2gb'
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
 