services:
  dev:
    build:
      context: .
      dockerfile: Dockerfile
      target: dev
    image: gelos-lc-dev
    environment:
      NB_UID: "${UID:-1000}"
      NB_GID: "${GID:-100}"
      NB_USER: jovyan
      CHOWN_HOME: "yes"
      CHOWN_HOME_OPTS: "-R"
      GRANT_SUDO: "yes"
      PYTHONPATH: /app
    working_dir: /app
    ports:
      - "${JUPYTER_HOST_PORT:-8888}:8888"
      - "${DASK_HOST_PORT:-8787}:8787"
    volumes:
       - ./:/app/ 
       - "${RAW_PATH}:/app/data/raw/"
       - "${PROCESSED_PATH}:/app/data/processed/"
       - "${EXTERNAL_PATH}:/app/data/external/"
       - "${INTERIM_PATH}:/app/data/interim/"
       - "${GELOS_MODULE_PATH}:/app/gelos/"
    shm_size: '32gb'
    command: "pixi run start-notebook.py ${JUPYTERLAB_ARGS}"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
  test:
    build:
      context: .
      dockerfile: Dockerfile
      target: test
    image: gelos-lc-test
    environment:
      PYTHONPATH: /app
    working_dir: /app
    volumes:
      - ./:/app/ 
      - "${GELOS_MODULE_PATH}:/app/gelos/" # until gelos is public, then change Dockerfile
  prod:
    build:
      context: .
      dockerfile: Dockerfile
      target: prod
    image: gelos-lc-prod
    environment:
      PYTHONPATH: /app
    working_dir: /app
    volumes:
      - ./:/app/ 
      - "${RAW_PATH}:/app/data/raw/"
      - "${PROCESSED_PATH}:/app/data/processed/"
      - "${EXTERNAL_PATH}:/app/data/external/"
      - "${INTERIM_PATH}:/app/data/interim/"
      - "${GELOS_MODULE_PATH}:/app/gelos/" # until gelos is public, then change Dockerfile
    shm_size: '2gb'
 