experiment_name: "AlphaEarth Annual (Center Patch)"
data_version: "v0.50.1"
chip_tracker: "gelos_chip_tracker.geojson"
chip_id_column: "id"
null_handling: zero

data:
  class_path: gelos.gelosdatamodule.GELOSDataModule
  init_args:
    dataset_class: src.gelosdataset_lc.GELOSLCDataSet
    batch_size: 1
    num_workers: 0
    bands:
      S2L2A:
        - BLUE
        - GREEN
        - RED

cloud_embedding:
  backend: alphaearth
  reference_sensor: S2L2A
  patch_size: 16
  year_strategy:
    type: from_filename
    sensor: S2L2A
    pattern: '_(\d{4})\d{4}\.tif$'
  init_args: {}
  extraction_strategies:
    middle_patch:
      title: "AlphaEarth Annual (Center Patch)"
      patches: center_1x1
      pool: flatten

embedding_extraction_strategies:
  middle_patch:
    title: "AlphaEarth Annual (Center Patch)"
    slice_args:
      - {start: 0, stop: null, step: 1}
    transforms:
      - type: tsne
      - type: umap
    metrics:
        - type: pca_ablation
          params:
            variance_thresholds: [0.8, 0.85, 0.9, 0.95, 0.99]
        - type: knn_purity
          params:
            k_values: [1, 2, 5, 10, 20, 50]
    plots:
      - type: scatter_2d
        transform: tsne
        params:
          axis_lim: 160
      - type: scatter_2d
        transform: umap
        params:
          axis_lim: 

style:
  category_column: "lulc"
  colors:
    "1":  "#419bdf"
    "2":  "#397d49"
    "5":  "#e49635"
    "7":  "#c4281b"
    "8":  "#a59b8f"
    "11": "#e3e2c3"
  labels:
    "1":  "Water"
    "2":  "Trees"
    "5":  "Crops"
    "7":  "Built Area"
    "8":  "Bare Ground"
    "11": "Rangeland"
